name: hover_material_button
description: "Hover Material Button is a Flutter package that provides a Material Button that can be hovered over to show a tooltip."
#publish_to: 'none'
repository: https://github.com/juneview-songdo/hover_material_button

version: 1.0.4

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  after_layout:
  bot_toast:
  device_preview:
  flutter:
    sdk: flutter
  flutter_screenutil:
  flutter_svg:
  flutter_zoom_drawer:
  gap:
  go_router:
  june:
  june_flow_util:
  keyboard_attachable:
  modal_bottom_sheet:
  styled_widget:

dev_dependencies:
  bot_toast_module:
  device_preview_module:
  flutter_lints:
  flutter_lints_module:
  flutter_test:
    sdk: flutter
  june_view: #@add
  june_view_more:  #@add
  screenutil_module:

flutter:
  assets:
    - assets/view/hover_material_button/feedback-svgrepo-com.svg
  uses-material-design: true